### ISSUE TITLE
Install and Usage behind reverse proxy scenario

### ISSUE THREAD

**Issue by hannesaddec** [geopython/GeoHealthCheck#27] opened 2015-10-13 12:02 UTC
Installation in a scenario on a windows machine behind a reverse proxy with authentication. Issues and code suggestion are below. If a PR is needed for suggestion 3 let me know. 

Issue 1:
Executing <<paver setup>> - excerpt from the messages
```
......
stall\virtualenvironment\geohealthcheck\lib\site-packages (from Flask->Flask-Log
in==0.2.11->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in g:\inst
all\virtualenvironment\geohealthcheck\lib\site-packages (from Flask->Flask-Login
==0.2.11->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in g:\install
\virtualenvironment\geohealthcheck\lib\site-packages (from python-dateutil>=1.5-
>OWSLib->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in g:\insta
ll\virtualenvironment\geohealthcheck\lib\site-packages (from Jinja2>=2.4->Flask-
>Flask-Login==0.2.11->-r requirements.txt (line 1))
```

Captured Task Output:
---------------------
```
---> pavement.setup
pip install -r requirements.txt
Traceback (most recent call last):
  File "g:\install\virtualenvironment\geohealthcheck\lib\site-packages\paver\tas
ks.py", line 196, in _run_task
    return do_task()
  File "g:\install\virtualenvironment\geohealthcheck\lib\site-packages\paver\tas
ks.py", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 87, in setup
    zipstr = StringIO(urlopen(skin).read())
  File "G:\apps\Python27\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\apps\Python27\Lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "G:\apps\Python27\Lib\urllib2.py", line 449, in _open
    '_open', req)
  File "G:\apps\Python27\Lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "G:\apps\Python27\Lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "G:\apps\Python27\Lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:590)>
```

All requirements are satisfied - I believe its due to the downloading of files from pavement.py - line ~73..106 .. I performed the steps manually and it compiled afterwards. There are plenty of websites with issues with the certificate problem, however I'm wondering if the iostring used is aware of the reverse proxy authentication set outside via SET HTTPS_PROXY or SET HTTP_PROXY

Issue 2:

To run the application inside an closed system I suggest to move the leaflet CDN/IE9 code in to a local file (e.g. static/lib ) so following code changes for 

add to layout.html 
L15		<link href="{{ url_for('static', filename='lib/leaflet-0.6.4/leaflet.css') }}" rel="stylesheet">
L20+21   <script src="{{ url_for('static', filename='lib/html5shiv.min.js') }}"></script>
		<script src="{{ url_for('static', filename='lib/respond.min.js') }}"></script>
L112        <script src="{{ url_for('static', filename='lib/leaflet-0.6.4/leaflet.js') }}"></script> 

and to be added in setup() in pavement.py for downloading these files.

Issue 3:

Add on feature - WMS service configurable in the config.py so the site background WMS can be specified.  

1) add to config.py in line 44
GHC_BACKGROUNDWMS_URL = 'http://otile{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png'
GHC_BACKGROUNDWMS_CENTER_LAT = 1.1
GHC_BACKGROUNDWMS_CENTER_LON =1.1
GHC_BACKGROUNDWMS_MAXZOOM = 2
GHC_BACKGROUNDWMS_SUBDOMAINS = '1234'

2) in templates\home.html  line 184 ff replace current by 
var map = L.map('all-resources-map').setView([{{ config['GHC_BACKGROUNDWMS_CENTER_LAT'] }},{{ config['GHC_BACKGROUNDWMS_CENTER_LON'] }}], 1);
  
	 map.addLayer(new L.TileLayer(
        '{{ config['GHC_BACKGROUNDWMS_URL'] }}', {
            maxZoom: {{ config['GHC_BACKGROUNDWMS_MAXZOOM'] }},
            subdomains: '{{ config['GHC_BACKGROUNDWMS_SUBDOMAINS'] }}'
        }
    ));

3)  in templates\resources.html line 184 ff  replace current by 

 map.addLayer(new L.TileLayer(
        '{{ config['GHC_BACKGROUNDWMS_URL'] }}', {
            maxZoom: {{ config['GHC_BACKGROUNDWMS_MAXZOOM'] }},
            subdomains: '{{ config['GHC_BACKGROUNDWMS_SUBDOMAINS'] }}'
        }
    ));

**Comment by tomkralidis** [comment] 2015-10-13 18:03
@hannesaddec: thanks for the report.

- item 1: I can't reproduce the issue.  which sites are having SSL issues?
- items 2 and 3 implemented in master

In the future, it would be helpful, if possible, to 1./ separate the issues into separate GitHub issues 2./ provide pull requests for enhancements.

**Comment by hannesaddec** [comment] 2015-10-13 18:43
Thanks for the implementation for 2 and 3.
For 1 -> the URLs from https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/archive/v1.0.3.zip and 'http://ejohn.org/files/jspark.js did not work. I had issues with python and reverse proxies with authentication before. 
for separation and single PR - will do in the future

**Comment by tomkralidis** [comment] 2015-10-13 19:18
@hannesaddec thanks.  Localized build additions added in 485a9afcd2527f54b91b99b6bb299d50642740ea

I'll close this ticket for now given most of the issues are covered/implemented.  For the proxy issues, please open a specific ticket as I'm guessing this will take some work to track down/fix.

**Closed by tomkralidis** 2015-10-13 19:18 UTC
